baseurl = "/"
title = "R-mageddon"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "Mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Author]
    name = "Tomas Westlake"
    bio = "Data Scientist for the UK Government"
    avatar = "img/avatar.png"


[Params]
    subtitle = "I've not failed, I've just found 10,000 ways that won't work." # Subtitle of your site
    description = "Tom Westlake's personal blog about R related funtivities" # Description of your site
    opengraph = true
    twitter_cards = true
    readmore = false # Show "Read more" button in list if true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = true
    post_navigation = true
    postSections = ["post"]


[Params.widgets]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent arcticles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
        tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)
        
    
    social_twitter = "tomwestlake121"
    social_linkedin = "tomas-westlake-56484a45"
    social_github = "tomwestlake121"
    social_email = "tom.westlake121@gmail.com"
 
